### ISSUE TITLE
Xamarin.Forms Quickstarter/Project Template

### ISSUE THREAD

**Issue by mzhukovs** [WaveEngine/QuickStarters#7]
According to your [blog post](https://geeks.ms/waveengineteam/2017/08/21/whats-new-in-wave-engine-2-4-0), as of v2.4 the UWP platform should have an additional Launcher Type option for Xamarin.Forms - however, I just installed v2.5 of WaveEditor and this option does not appear for me - any ideas?

Also, this seems a strange place to put that option since Xamarin.Forms is cross-platform and can cover UWP, iOS, and Android, but I don't really care that much about that so long as it is supported, just thought I'd point that out!

**Comment by pulimento** [comment]
Hello @mzhukovs !

First of all, thanks for trying out our code. As you said, it made no sense create a Xamarin.Forms project straight from the editor. We have an (now) unoficially supported template, you can find it in https://github.com/jsuarezruiz/xamarin-forms-waveengine-sample. Let us now if you have some issues. I'll keep this issue open by now.
